export const PRICING_PLANS = [
  {
    id: "free",
    period: "",
    name: "Free Plan",
    oldMonthlyPrice: 0,
    currencyType: "USD",
    price: 0,
    usdRate: 1525,
    features: [
      { id: 1, label: "5 Book Summary" },
      { id: 2, label: "Create up to 15 notes" },
      { id: 3, label: "10 Custom Reminders" },
      { id: 4, label: "15 Smart Searches" },
    ],
    buttonText: "Free Plan",
    isPopular: false,
  },
  {
    id: "basic",
    period: "monthly",
    packageAppleId: "BookFlowBasic",
    name: "Basic Plan",
    oldMonthlyPrice: 8,
    currencyType: "USD",
    price: 4.99,
    usdRate: 1525,
    features: [
      { id: 1, label: "15 Book Summaries" },
      { id: 2, label: "Create up to 30 notes" },
      { id: 3, label: "20 Custom Reminders" },
      { id: 4, label: "15 Smart Searches" },
    ],
    buttonText: "Get Started",
    isPopular: false,
  },
  {
    id: "premium",
    period: "monthly",
    packageAppleId: "BookFlowPremium",
    name: "Premium Plan",
    oldMonthlyPrice: 15,
    currencyType: "USD",
    price: 9.99,
    usdRate: 1525,
    features: [
      { id: 1, label: "25 Book Summaries" },
      { id: 2, label: "Create up to 45 notes" },
      { id: 3, label: "30 Custom Reminders" },
      { id: 4, label: "25 Smart Searches" },
    ],
    buttonText: "Get Started",
    isPopular: true,
  },
  {
    id: "scholar",
    packageAppleId: "BookFlowScholar",
    period: "monthly",
    name: "Scholar Plan",
    oldMonthlyPrice: 45,
    currencyType: "USD",
    price: 29.99,
    usdRate: 1525,
    features: [
      { id: 1, label: "50 Book Summaries" },
      { id: 2, label: "Create unlimited notes" },
      { id: 3, label: "Unlimited Custom Reminders" },
      { id: 4, label: "70 Smart Searches" },
    ],
    buttonText: "Get Started",
    isPopular: false,
  },
] as const;

export type PricingPlan = (typeof PRICING_PLANS)[number];
